# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# How do I allow non-mandatory params
# How do I pass params from external input
parameters:
- name: packageIds
  type: string
  default: ""   

- name: listenerStatus
  type: string
  default: 'RUNNING'

variables:
- group: boomicicd

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # ... (existing script)

    source bin/publishPackagedComponentMetadata.sh \
      packageIds="${{ parameters.packageIds }}" \
      listenerStatus=${{ parameters.listenerStatus }}
    
  displayName: 'List all Components'
